<template>
  <div id="overlay">
    <div id="loading-icon">
      <div class="loadingio-spinner-rolling-j7wyz7is90q">
        <div class="ldio-9qfjo50uov">
          <div></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Loading",
  components: {},
  setup() {
    return {};
  }
});
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
#overlay {
  position: absolute;
  z-index: 10000;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background-color: rgba(255, 255, 255, 0.1);
}

#loading-icon {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

  @keyframes ldio-9qfjo50uov {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }

  .ldio-9qfjo50uov div {
    position: absolute;
    width: 30px;
    height: 30px;
    border: 5px solid white;
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-9qfjo50uov div {
    animation: ldio-9qfjo50uov 0.8695652173913042s linear infinite;
    top: 100px;
    left: 100px;
  }
  .loadingio-spinner-rolling-j7wyz7is90q {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: rgba(0, 0, 0, 0);
  }
  .ldio-9qfjo50uov {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-9qfjo50uov div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
}
</style>
